# TCL File Generated by Component Editor 15.0
# Mon May 23 23:23:10 CEST 2016
# DO NOT MODIFY


# 
# sextium_ram_avalon "sextium_ram_avalon" v1.0
#  2016.05.23.23:23:10
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module sextium_ram_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME sextium_ram_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Sextium helper"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sextium_ram_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sextium_ram_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sextium_ram_avalon.v VERILOG PATH sextium_ram_avalon.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL sextium_ram_avalon
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sextium_ram_avalon.v VERILOG PATH sextium_ram_avalon.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1
add_interface_port reset reset_req reset_req Input 1


# 
# connection point ram
# 
add_interface ram conduit end
set_interface_property ram associatedClock clock
set_interface_property ram associatedReset ""
set_interface_property ram ENABLED true
set_interface_property ram EXPORT_OF ""
set_interface_property ram PORT_NAME_MAP ""
set_interface_property ram CMSIS_SVD_VARIABLES ""
set_interface_property ram SVD_ADDRESS_GROUP ""

add_interface_port ram mem_address address Output 16
add_interface_port ram mem_byteena byteena Output 2
add_interface_port ram mem_clock clock Output 1
add_interface_port ram mem_clocken clocken Output 1
add_interface_port ram mem_data data Output 16
add_interface_port ram mem_wren wren Output 1
add_interface_port ram mem_q q Input 16


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 131072
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave address address Input 16
add_interface_port slave byteenable byteenable Input 2
add_interface_port slave chipselect chipselect Input 1
add_interface_port slave clken clken Input 1
add_interface_port slave write write Input 1
add_interface_port slave writedata writedata Input 16
add_interface_port slave readdata readdata Output 16
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0

