# TCL File Generated by Component Editor 15.0
# Fri May 06 23:11:17 CEST 2016
# DO NOT MODIFY


# 
# sextium_avalon_mem "sextium_avalon_mem" v1.1
#  2016.05.06.23:11:17
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module sextium_avalon_mem
# 
set_module_property DESCRIPTION ""
set_module_property NAME sextium_avalon_mem
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Sextium helper"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sextium_avalon_mem
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sextium_avalon_mem
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file sextium_avalon_mem.v VERILOG PATH sextium_avalon_mem.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL sextium_avalon_mem
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file sextium_avalon_mem.v VERILOG PATH sextium_avalon_mem.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master writedata writedata Output 16
add_interface_port avalon_master readdata readdata Input 16
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master address address Output 32
add_interface_port avalon_master waitrequest waitrequest Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point sextium_mem
# 
add_interface sextium_mem conduit end
set_interface_property sextium_mem associatedClock clock_sink
set_interface_property sextium_mem associatedReset reset_sink
set_interface_property sextium_mem ENABLED true
set_interface_property sextium_mem EXPORT_OF ""
set_interface_property sextium_mem PORT_NAME_MAP ""
set_interface_property sextium_mem CMSIS_SVD_VARIABLES ""
set_interface_property sextium_mem SVD_ADDRESS_GROUP ""

add_interface_port sextium_mem addr_bus addr_bus Input 16
add_interface_port sextium_mem mem_bus_in mem_bus_in Output 16
add_interface_port sextium_mem mem_bus_out mem_bus_out Input 16
add_interface_port sextium_mem mem_read mem_read Input 1
add_interface_port sextium_mem mem_write mem_write Input 1
add_interface_port sextium_mem mem_ack mem_ack Output 1

