# TCL File Generated by Component Editor 15.0
# Sun May 08 21:31:37 CEST 2016
# DO NOT MODIFY


# 
# sextium_avalon_io "sextium_avalon_io" v1.0
#  2016.05.08.21:31:37
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module sextium_avalon_io
# 
set_module_property DESCRIPTION ""
set_module_property NAME sextium_avalon_io
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Sextium helper"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sextium_avalon_io
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sextium_avalon_io
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file sextium_avalon_io.v VERILOG PATH sextium_avalon_io.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL sextium_avalon_io
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file sextium_avalon_io.v VERILOG PATH sextium_avalon_io.v


# 
# parameters
# 
add_parameter READ_FIFO_ADDR STD_LOGIC_VECTOR 0 ""
set_parameter_property READ_FIFO_ADDR DEFAULT_VALUE 0
set_parameter_property READ_FIFO_ADDR DISPLAY_NAME READ_FIFO_ADDR
set_parameter_property READ_FIFO_ADDR WIDTH 32
set_parameter_property READ_FIFO_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property READ_FIFO_ADDR UNITS None
set_parameter_property READ_FIFO_ADDR DESCRIPTION ""
set_parameter_property READ_FIFO_ADDR HDL_PARAMETER true
add_parameter WRITE_FIFO_ADDR STD_LOGIC_VECTOR 2 ""
set_parameter_property WRITE_FIFO_ADDR DEFAULT_VALUE 2
set_parameter_property WRITE_FIFO_ADDR DISPLAY_NAME WRITE_FIFO_ADDR
set_parameter_property WRITE_FIFO_ADDR WIDTH 32
set_parameter_property WRITE_FIFO_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property WRITE_FIFO_ADDR UNITS None
set_parameter_property WRITE_FIFO_ADDR DESCRIPTION ""
set_parameter_property WRITE_FIFO_ADDR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address address Output 32
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master readdata readdata Input 16
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master writedata writedata Output 16


# 
# connection point sextium_io
# 
add_interface sextium_io conduit end
set_interface_property sextium_io associatedClock clock
set_interface_property sextium_io associatedReset ""
set_interface_property sextium_io ENABLED true
set_interface_property sextium_io EXPORT_OF ""
set_interface_property sextium_io PORT_NAME_MAP ""
set_interface_property sextium_io CMSIS_SVD_VARIABLES ""
set_interface_property sextium_io SVD_ADDRESS_GROUP ""

add_interface_port sextium_io io_bus_in io_bus_in Output 16
add_interface_port sextium_io io_bus_out io_bus_out Input 16
add_interface_port sextium_io io_read io_read Input 1
add_interface_port sextium_io io_write io_write Input 1
add_interface_port sextium_io io_ack io_ack Output 1

